### ISSUE TITLE
"Submit Delete My Data Request" is triggered even if you click to the right of the button

### ISSUE THREAD

**Issue by rshin** [brownhci/drafty#175]
On https://drafty.cs.brown.edu/account, I believe the `click` event handler is set on the wrong element, which means that you can click on empty space near the button accidentally and the request will be submitted.

https://github.com/brownhci/drafty/blob/27941b02574ec38b2aa8baa52af2ab740beb08c6/backend/src/public/js/deleteuserdata.ts#L2
could be replaced with something like
`const deleteUserDataForm = document.querySelector('#delete-data-form > button');`

**Comment by swallace21** [comment]
Ah, nice catch! Thank you. :)

The code commit (going live soon) just grads the button:
c0f4db95c70a52e1e9dd5ffeb02818ccb797d154
