### ISSUE TITLE
csopenrankings: sorting using geometric average?

### ISSUE THREAD

**Issue by osalbahr** [brownhci/drafty#192]
Hi! I find https://drafty.cs.brown.edu/csopenrankings a very interesting way to quickly find which schools have faculty that are more active in certain fields.

I noticed that the sorting of the list is based on adding up the numbers. Thoughts on adding an option that uses the geometric mean instead? The idea is reducing the effect of outliers.

**Comment by jeffhuang** [comment]
Yup, I think that would be fine and perhaps mathematically better, but the tradeoff is visitors may be confused about how it works as it would require any extra explanation. So we opted for a simple way to add that would easily be understood by any visitor and be reasonable-sounding enough.

**Comment by osalbahr** [comment]
Good point. Yeah, I agree that it’s a good idea to keep the default simple, and adding an option is probably not worth the hassle. I will probably just use a simple Google Sheet out of curiosity (I doubt there would be any substantial change). Thank you!

**Comment by osalbahr** [comment]
Good point. Yeah, I agree that it’s a good idea to keep the default simple, and adding an option is probably not worth the hassle. I will probably just use a simple Google Sheet out of curiosity (I doubt there would be any substantial change). Thank you!
