### ISSUE TITLE
csopenrankings: "Show Only Canadian Universities" option in dropdown

### ISSUE THREAD

**Issue by 0foxes** [brownhci/drafty#208]
Hi, is it possible to add an option to only display Canadian universities? The website allows selection between US+Canada and US-Only right now. I know Canadian universities have italicised names, but it's hard to scroll down the list and pick out all of them.

![image](https://github.com/brownhci/drafty/assets/31290848/3938dd33-7287-4074-873e-ba4eb7b1b270)

**Comment by swallace21** [comment]
That's a good suggestion. I can add it to the features we will be implementing/improving in the future. Thanks! :)

**Comment by swallace21** [comment]
All set btw. The change is live.

**Comment by 0foxes** [comment]
Super helpful, thanks! I went to the site and it doesn't show any
universities yet, but I assume it's still updating.

**Comment by swallace21** [comment]
Try again, the table is showing up on multiple browsers/devices.

**Comment by 0foxes** [comment]
Hmm, I tried on my phone/laptop and the table was blank. This archive
capture shows what I see:

https://archive.is/K63uo

**Comment by jeffhuang** [comment]
Yeah I am seeing the issue too. The javascript error is:

```
Uncaught TypeError: Cannot read properties of null (reading 'replaceWith')
    at createTable (app.js:478:16)
    at app.js:16:5
```

**Comment by swallace21** [comment]
Thanks Anthony. I see it is blank now too. Jeff, I saw that error
earlier today. Fixed it. Re-ran the build table crown jobs and the error
did not come back. I'll have to dig deeper to find the root cause. Thanks
everyone!

**Comment by swallace21** [comment]
all set

**Comment by 0foxes** [comment]
Awesome, thanks! When I display "Canadian only" it shows all their "US
News" rankings as 211, is that intentional?

**Comment by swallace21** [comment]
not intentional, all set
